{{/*
Standard Kubernetes Service
Usage: {{ include "common.service.standalone" . }}
*/}}
{{- define "common.service.standalone" -}}
{{- include "common.withMergedValues" (dict "templateName" "common.service" "context" .) -}}
{{- end -}}

{{- define "common.service" -}}
{{- /* Service defaults */}}
{{- $serviceType := .Values.service.type | default "ClusterIP" -}}
{{- $servicePort := .Values.service.port | default 80 -}}
{{- $targetPort := .Values.service.targetPort | default 3000 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ $serviceType }}
  ports:
    - port: {{ $servicePort }}
      targetPort: {{ $targetPort }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}
{{- end -}}
