{{/*
Complete web application deployment bundle
Includes: deployment, service, ingress, secrets, image pull secrets, and security headers
Usage: {{ include "common.web" . }}
*/}}
{{- define "common.web" -}}
{{ include "common.deployment.standalone" . }}
---
{{ include "common.service.standalone" . }}
---
{{ include "common.ingress.standalone" . }}
---
{{ include "common.headers.standalone" . }}
---
{{ include "common.externalSecret.standalone" . }}
---
{{ include "common.imagePullSecret.standalone" . }}
---
{{ include "common.namespace.standalone" . }}
{{- end -}}
